---
- name: Prepare the system for Slurm
  hosts: localhost

  tasks:
  - name: Create slurm user
    ansible.builtin.user:
      name: slurm
      state: present
  - name: Create slurmctld directory
    file:
      path: /var/spool/slurmctld
      state: directory
      owner: slurm
      mode: 0700
  - name: Create slurmd directory
    file:
      path: /var/spool/slurmd
      state: directory
      owner: slurm
      mode: 0700
  - name: Create slurmd directory
    file:
      path: /var/run/slurm
      state: directory
      owner: slurm
      mode: 0700
  - name: Create slurm log directory
    file:
      path: /var/log/slurm
      state: directory
      owner: slurm
      mode: 0700
  - name: Creating "/etc/tmpfiles.d/slurm.conf"
    copy:
      dest: "/etc/tmpfiles.d/slurm.conf"
      content: |
        d /run/slurm 0770 root slurm -
  - name: Install MySQL
    apt:
      pkg:
        - mysql-server
        - mysql-client
        - libmysqlclient-dev
      state: latest
      update_cache: true
  - name: Create "slurm_acct_db" database
    community.mysql.mysql_db:
      name: slurm_acct_db
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock
  - name: Create slurm MySQL user
    community.mysql.mysql_user:
      name: slurm
      password: slurmdb_passwort
      priv: '*.*:ALL'
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock
  - name: Install mailutils  (state=present is optional)
    ansible.builtin.apt:
      name: mailutils
      state: present
